---
title: "Planificación"
sidebar: false
toc: false
page-layout: full
---

Los dos componentes centrales del curso son las clases teóricas y las actividades prácticas. Las **clases** se realizarán los días **Viernes  09:00 a 10:50** en sala **329**


- [**Clases**]() (<i class="fas fa-chalkboard-teacher"></i> ): Lecturas, documentos de presentación y video (en caso que la sesión sea grabada)

- [**Prácticas y evaluaciones**]() (<i class="fas fa-user-edit"></i>): Actividades prácticas a desarrollar durante la semana.

- [**Lecturas**]() (<i class="fas fa-book-reader"></i>): Llegar a la clase con los textos leídos.



| |<i class="fas fa-chalkboard-teacher"></i>  Clases  |  <i class="fas fa-user-edit"></i>  Prácticas y evaluaciones | <i class="fas fa-book-reader"></i> Lecturas y material adicional
-----|----|-----------|-----------
<font color="orange"> **Marzo** </font> |   |   |
Viernes 17 | [**00. Presentación**](/content/01-content.html) e [**01. introducción**](/content/02-content.html)  | [**1. Aproximación inicial a R**](/resource/01-resource.html)  | - Leer detalladamente [programa del curso](syllabus.html)

### UNIDAD 1: Estadística descriptiva

|||
-----|----|-----------|-----------
Viernes 24 | [**2.Operacionalización de variables **](/content/03-content.html)   |  [**2.Operacionalización de variables**](/resource/02-resource.html) | - [Wickham & Grolemund, (2017). cap. 1 Introducción](https://es.r4ds.hadley.nz/introducci%C3%B3n.html) <br>
Viernes 31 | [**3. Visualización de datos**](/content/03-content.html)  | -  | - [Wickham & Grolemund, (2017). cap. 2 Explorar](https://es.r4ds.hadley.nz/explorar-introduccion.html)
<font color="orange"> **Abril** </font> |   |   |
Viernes 07 | Viernes santo  |   |
Viernes 14 | 1° semana presencial  |   |
Viernes 21 |   | Evaluación  |  |

### UNIDAD 2: Estadística Correlacional

|||
-----|----|-----------|-----------
Viernes 28 | [**4. Introducción a la inferencia estadística**](/content/05-content.html)  |   |
<font color="orange"> **Mayo** </font> |   |   |
Viernes 05 | 1° semana de pausa reflexiva  |   |
Viernes 12 | [**5. Correlación**](/content/06-content.html)  |   | 
Viernes 19 | [**6. Índices y análisis factorial**](/content/07-content.html)  |   | 
Viernes 26 | 2° semana presencial  |   |

### UNIDAD 3: Regresión lineal y regresión logística

|||
-----|----|-----------|-----------
<font color="orange"> **Junio** </font> |   |   |
Viernes 02 | [**7. Regresión lineal de mínimos cuadrados**]() | |  |
Viernes 09 | 2° semana de pausa reflexiva  |   |
Viernes 16 | [**8. Regresión logística binaria: interpretación de coeficientes y cálculo de probabilidades]()  |   | 
Viernes 23 | [**10. Análisis factorial y regresión lineal en R**](https://metod1-mcs.netlify.app/content/11-content.html)  |   | 
Viernes 30 | [**11. Supuestos de regresión y valores predichos**](https://metod1-mcs.netlify.app/content/12-content.html)   |   | 
<font color="orange"> **Julio** </font> |   |   |
Viernes 07 | 3° semana presencial  |   |
Viernes 14 |   | Evaluación  |  |
