---
title: Programa
lang: es
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

::: {.grid .course-details .course-details-smaller}

::: {.g-col-6}
### Profesor

- {{< fa user >}} &nbsp; [{{< var instructor.name >}}]({{< var instructor.url >}})
- {{< fa university >}} &nbsp; {{< var instructor.office >}}
- {{< fa envelope >}} &nbsp; <a href="mailto:{{< var instructor.email >}}">{{< var instructor.email >}}</a>
- {{< fa brands twitter >}} &nbsp; [{{< var instructor.twitter >}}](https://www.twitter.com/{{< var instructor.twitter >}})
- {{< fa calendar-check >}} &nbsp; [Schedule an appointment]({{< var instructor.appointment_url >}})
:::

::: {.g-col-6}
### Información del curso

- {{< fa calendar >}} &nbsp; {{< var course.days >}}
- {{< fa calendar-alt >}} &nbsp; {{< var course.dates >}}
- {{< fa clock >}} &nbsp; {{< var course.time >}}
- {{< fa location-dot >}} &nbsp; {{< var course.location >}}
- {{< fa brands slack >}} &nbsp; [Slack]({{< var course.slack >}})
:::

:::

## Resumen

Este curso busca dar un primer acercamiento a la investigación social cuantitativa, abarcando desde aspectos iniciales básicos de estadística descriptiva y visualización de datos, hasta análisis e interpretación de modelos explicativos de investigación social. Asimismo, se busca que los y las estudiantes logren familiarizarse con el uso de Rstudio para el análisis de datos sociales.

La metodología incluye clases lectivas y trabajo práctico en R.


## Objetivo general

Al finalizar el curso, el/la estudiante podrá elaborar y analizar diseños de investigación social de carácter cuantitativo, así como describir cuantitativamente un conjunto de datos utilizando el lenguaje R.


## Objetivos específicos

Al concluir el curso lo/as estudiantes deberán haber alcanzado los siguientes resultados de aprendizaje:


- Conocer las etapas de un diseño de investigación social cuantitativa y sus principales elementos


- Formular diseños de investigación social cuantitativa


- Conocer y aplicar instrumentos de medición y tipos de estudios cuantitativos
- Interpretar y analizar los elementos centrales de una base de datos con información social


- Aplicar e interpretar técnicas de estadística descriptiva según las distintas características de los datos


- Aplicar e interpretar técnicas de estadística correlacional e inferencia estadística para variables con distinta unidad de medida


- Aplicar e interpretar técnicas de regresión lineal y logística para variables numéricas y variables categóricas



## Saberes / contenidos

### Módulo 1: Estadística descriptiva


1.1  Elementos básicos de la investigación social

- Etapas de la investigación Social

- Tipos de diseños

- Diseño de instrumentos de medición

- Bases de datos: datos de corte transversal, series de tiempo, cohortes, panel o longitudinal


1.2 Operacionalización y análisis de datos

- Operacionalización y niveles de medición

- Tidy data: unir, dividir, filtrar y ordenar datos en R

- Recodificación de variables: descriptivos básicos, casos perdidos, etiquetamiento de variables

- Agrupación de datos y construcción de variables a partir de datos existentes

- Construcción de índices y validez de escalas


1.3 Visualización de datos en R

- Tablas descriptivas y tablas de contingencia

- ggplot2: gráficos de barra, de caja, dispersión e histograma


### Módulo 2: Inferencia y estadística correlacional

2.1 Inferencia estadística

2.2 Pruebas de hipótesis

2.3 Correlación


### Módulo 3: Regresión lineal y regresión logística

3.1 Regresión lineal de mínimos cuadrados

- Aspectos centrales y supuestos de la regresión MCO

- Interpretación de coeficientes (variables cuantitativas y cualitativas) y efectos de interacción 

- Representación gráfica de coeficientes de regresión lineal


3.2 Regresión logística binaria

- Aspectos básicos de la regresión logística

- Tipos de coeficientes e interpretación

- Representación gráfica (cálculo de probabilidades predichas) 

## Bibliografía

Wickham, Hadley & Grolemund, Garrett (2017). R for Data Science. Visualize, model, transform, tidy and import data. / Versión en español disponible [acá](https://es.r4ds.hadley.nz/)

[Moore, D. S., & Comas, J. (2010). Estadística aplicada básica. Barcelona: Antoni Bosch.](resource/moore2010.pdf)

[Wooldridge, J. M. (2008). Introducción a la econometría: un enfoque moderno. Paraninfo Cengage Learning.](wooldridge2008)

[Camarero, et al (2017) Regresión Logística: Fundamentos y aplicación a la investigación sociológica.](https://www2.uned.es/socioestadistica/Multivariante/Odd_Ratio_LogitV2.pdf)

Hair, Joseph F., et al. (2004). Análisis multivariante. 5ta ed. Madrid: Prentice Hall.

[Charte, Francisco (2014). Análisis exploratorio y Visualización de datos con R.](http://www.fcharte.com/libros/ExploraVisualizaConR-Fcharte.pdf)



## Metodología

El curso se organiza en sesiones semanales, con una parte lectiva seguida de una práctica. En la parte lectiva se transmiten y discuten los conceptos centrales de la investigación cuantitativa. En la parte práctica se aplicarán los conceptos transmitidos en la parte lectiva, además de resolver dudas en el avance de los trabajos de investigación

## Evaluación

La evaluación consistirá en 

## Requisitos de aprobación

- Nota mínima de aprobación: 4,0 (en escala de 1 a 7). 


## Palabras Clave 

- Estadística, investigación cuantitativa, manipulación de datos, visualización de datos, interpretación de coeficientes

