---
title: Trabajos
lang: es
---

# Presentación y directrices generales

La presente evaluación tiene por objetivo que las y los estudiantes apliquen de forma integral los
contenidos del curso a una temática de interés específica utilizando la base de datos del Estudio Social
Longitudinal de Chile (ELSOC) 2022. Se espera un ejercicio de investigación que logre dar cuenta del
aprendizaje de las herramientas de análisis estadístico que configuran las habilidades básicas para
desarrollar procesos de investigación social, analizando fuentes de información de carácter
cuantitativo desde una perspectiva sociológica.

## Cuestiones a considerar:

  1. El trabajo debe ser realizado en parejas.
  
  2. Se realizará una entrega final tipo reporte de investigación breve.

  3. Se recomienda que elaboren un problema de investigación que trate sobre las características sociales de algún problema actual de la sociedad chilena, y que sea factible de investigar con los datos del Estudio Social Longitudinal de Chile (ELSOC) 2022.
  
##   Instrucciones para el Informe
  
Para la entrega del informe se espera que, habiendo seleccionado un fenómeno específico de interés, se desarrollen los siguientes temas:
  
| **Componente**               | **Detalle**                                                                                                                                                                                                                                        | **Puntaje** |
|------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------|
| **Formulación del problema** | Formular una pregunta y un objetivo general de investigación. Fundamentar el interés sociológico que habilita el estudio de la temática elegida, utilizando al menos 3 referencias bibliográficas. El objetivo de investigación formulado debe permitir entender cómo se analizará la temática elegida. (1 plana) | 2.0         |
| **Definición base de datos** | Definir la fuente de información a utilizar indicando el nombre de la base de datos y la institución que la disponibiliza, la población que busca representar el estudio, el procedimiento de muestreo utilizado y el tamaño de la muestra. Dado que trabajaremos solo con el Estudio Social Longitudinal de Chile (ELSOC) 2022, se espera que las parejas describan qué busca medir y representar el módulo (o selección de variables) elegido. (½ plana) | 1.0         |
| **Operacionalización y descripción de variables** | Operacionalizar correctamente las variables de interés. Esta sección también incluye una tabla de descriptivos básicos, y una descripción detallada de la operacionalización y medición de las variables. - Tabla de descriptivos: etiquetas claras, debe ser posible identificar cada variable - Descripción de la operacionalización de cada variable y recodificación apropiada (por ejemplo, de menos a más presencia del atributo medido) | 3.0         |
| **Inferencia y Correlación** | Estimar, visualizar e interpretar los coeficientes de correlación entre variables. - Matriz de correlaciones (tabla): 1 - interpretación de tamaño de efecto: 1 - inferencia: 1                                                                                      | 3.0         |
| **Regresión lineal**         | Estimar, visualizar e interpretar coeficientes de regresión lineal - tabla de regresión: 0.5 - interpretación de coeficientes (interpretación de efectos de interacción es opcional, pero se valorará positivamente): 1 - inferencia/significación: 1 - ajuste global del modelo (R2): 0.5.      | 3.0         |
| **Regresión logística**      | Estimar, visualizar e interpretar coeficientes de regresión logística - tabla de regresión: 0.5 - interpretación coeficientes (interpretación de efectos de interacción es opcional, pero se valorará positivamente): 1 - inferencia: 1 - ajuste: 0.5      | 3.0         |
| **Conclusiones**             | En las conclusiones se deben sintetizar los aspectos más relevantes de los análisis estadísticos ya expuestos, articulando toda la información trabajada debe presentarse una respuesta tentativa a la pregunta de investigación. Además, debe reflexionar sobre los límites de su diseño de investigación y señalar posibles ejes de investigación que podrían ser considerados en futuras indagaciones (1 plana). | 2.0         |
| **Trabajo en R**             | Además del informe, entregar la carpeta con el Proyecto R, que contenga un archivo .Rproject, y las carpetas input, procesamiento y output. - La carpeta input debe contener la base de datos, manual de usuario, libro de códigos. - La carpeta procesamiento debe contener un archivo de sintaxis para el procesamiento y otro para el análisis de los datos. - La carpeta output debe contener la base de datos procesada y el resto de salidas asociadas (tablas, gráficos, etc.). - Se evaluará que los códigos utilizados generen las salidas (tablas, gráficos, etc.) que se presentan en el informe. | 1.0         |
 



## Aspectos formales  
  
Para la construcción del reporte de investigación por favor considere:

● El trabajo debe tener una portada que incluya: título, logo de la universidad, nombre de los
estudiantes, profesor/a, fecha y ayudantes.

● Debe incluirse un índice. Tablas, referencias y bibliografía utilizada debe presentarse en
formato APA.

● La fuente a utilizar debe ser Letra Times New Roman 12, interlineado simple y justificado.
Notas a pie de página en tamaño 10, en mismo formato que el texto central.

● El trabajo debe tener una redacción adecuada y sin errores de ortografía.

● Se descontarán hasta 5 décimas sobre la nota final por errores de este tipo.
  
## Fecha y formato de entrega 
  
El formato de entrega del informe debe ser un documento en formato PDF (.pdf), que debe estar
alojado en la carpeta output del Proyecto R. Fecha de entrega: jueves 18 de julio hasta las 12:00AM
vía módulo Tareas en plataforma U-Cursos.

● Entregas atrasadas hasta las 23:59 del jueves 18 de julio tendrán 0,5 puntos de descuento
sobre la nota final.

● Entregas atrasadas hasta el viernes 19 de julio hasta las 23:59 tendrán 1,0 punto de descuento
sobre la nota final. No serán evaluadas entregas posteriores a esta fecha.

## Sobre plagio

Todos los trabajos se procesan en software para detección de plagio: evidencia de una situación de
plagio implica obtención de la nota mínima en la evaluación (1,0) junto con constituirse como causal
de reprobación de la asignatura.

## Recomendaciones para la entrega

● Máxima de escritura: una idea por párrafo. Si comienza una idea nueva, se recomienda
comenzar otro párrafo. Al revés, si el párrafo siguiente habla de lo mismo, sumarlo al párrafo
anterior.

● La idea del párrafo se resume en la primera parte del párrafo, lo que en inglés se llama "topic
sentence".

● Declarar domicilio disciplinar: ej, mencionar la palabra "sociología" en el primer/segundo
párrafo, esto fuerza que la investigación se enmarque en la disciplina.

En caso de tener dudas, no dude en contactar a sus ayudantes respectivos, o bien, vía foro U-Cursos al
equipo docente de la asignatura.




